server:
  port: 8881

spring:
  application:
    name: order-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8889/eureka/,http://127.0.0.1:8890/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30

management:
  security:
    enabled: false
